spring.application.name=clientmanager

# Datasource
spring.datasource.url=jdbc:h2:file:./data/clientdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true



# Consola H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ========================================
# INTERNACIONALIZACIÓ (i18n)
# ========================================
# MessageSource per a messages.properties
spring.messages.basename=messages
spring.messages.encoding=UTF-8
spring.messages.fallback-to-system-locale=false

# Thymeleaf
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.mode=HTML
spring.thymeleaf.cache=false